dataframe: "../Data/arxiv_train.csv"


preprocess:
  max_len: 350

embedding:
  embedding_type: glove
  embedding_dim: 100
  freeze: True

model:
  rnn_type: lstm
  hidden_dim: 128
  bidirectional: true
  attention_layer: custom
  return_attn_weights: true
  num_layers: 2
  dropout: 0.3

training:
  lr: 0.001
  epochs: 10

batch_size: 64
output_dir: outputs/run1
log_dir: logs/run1
use_tensorboard: false
evaluate_on_test: false